[conf]
default-lang = "en"

[lang.en]
abstract = "Abstract"
glossary = "Glossary"
annex = "Annex"
appendix = "Appendix"
acknowledgments = "Acknowledgments"
note = "Note"
source = "Source"

[lang.pt]
abstract = "Resumo"
glossary = "Glossário"
annex = "Anexo"
appendix = "Apêndice"
acknowledgments = "Agradecimentos"
note = "Nota"
source = "Fonte"